import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Hasitha",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nappa vally",
      category: "Environment",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 0,
      rating: 4.5,
      numReviews: 10,
      description: "captured by mobile",
    },
    {
      name: "Honey spider",
      category: "Wildlife",
      image: "/images/p2.jpg",
      price: 120,
      countInStock: 10,
      rating: 3,
      numReviews: 10,
      description: "high quality DSLR image",
    },
    {
      name: "Purple Flowers",
      category: "Environment",
      image: "/images/p3.jpg",
      price: 120,
      countInStock: 10,
      rating: 3,
      numReviews: 10,
      description: "high quality DSLR image",
    },
    {
      name: "Misty Hills",
      category: "Environment",
      image: "/images/p4.jpg",
      price: 120,
      countInStock: 10,
      rating: 3,
      numReviews: 10,
      description: "high quality DSLR image",
    },
    {
      name: "Everest In Spring",
      category: "Environment",
      image: "/images/p5.jpg",
      price: 120,
      countInStock: 10,
      rating: 3,
      numReviews: 10,
      description: "high quality DSLR image",
    },
    {
      name: "Graffity B&W",
      category: "Environment",
      image: "/images/p6.jpg",
      price: 120,
      countInStock: 10,
      rating: 3,
      numReviews: 10,
      description: "high quality Mobile image",
    },
  ],
};

export default data;
